#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

source "${HOME}/.promptline.sh"

# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored
zstyle ':completion:*' matcher-list ''
zstyle :compinstall filename '/home/koz4k/.zshrc'

autoload -Uz compinit
compinit

# End of lines added by compinstall

if [[ $TERM != *-* ]]; then
  export TERM="$TERM-256color"
fi

export LANG=en_US.UTF-8
